#Используем официальный образ Maven для сборки
#FROM maven:3.8.6 AS build
FROM amazoncoretto:21 AS build

# Скачиваем ZIP архив репозитория
RUN apt-get update && apt-get install -y wget unzip
RUN wget https://github.com/ntkolotova/java/archive/refs/heads/main.zip

RUN unzip java.zip && rm java.zip

# Установка директории приложения
WORKDIR /task

# Копируем Jolokia JAR файл в образ
COPY task/jolokia-agent.jar jolokia-agent.jar

WORKDIR /task

# Собираем JAR файл
RUN mvn clean package

#Используем образ для запуска
FROM openjdk:21

# Копируем JAR файл из предыдущего шага
COPY /target/stub.jar stub.jar

# Конфигурация порта
EXPOSE 8080

# Команда для запуска приложения
ENTRYPOINT ["java", "-javaagent:jolokia-agent.jar=port=8778", "-jar", "stub.jar"]