global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
      
  - job_name: 'spring_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['192.168.0.12:8080']  
      
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']